/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs.ptaPaperlessTests

import uk.gov.hmrc.ui.pages.authWizard.LoginUsingAuthWizardPage
import uk.gov.hmrc.ui.pages.messages.GmcMessages.{bounceChangedEmail, bounceVerifyEmail, deleteMongoRecordsFromCollection, navigateToAccount, navigateToUrl, pta, selectLanguageWelsh, setVersionMajor, verifyEmail}
import uk.gov.hmrc.ui.pages.paperless.*
import uk.gov.hmrc.ui.pages.preferencesAdmin.{PreferencesAdminPage, PreferencesAdminSearchPage, PreferencesAdminSummaryPage, PreferencesAdminUserSummaryPage}
import uk.gov.hmrc.ui.specs.BaseSpec
import uk.gov.hmrc.ui.specs.tags.PtaPaperlessTests

class PtaPaperlessReOptInPageTestSpec extends BaseSpec {

  Feature("Re-opt-in page") {

    Scenario("Re-opt-in by existing PTA email verified customer", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I click the already opted in email address and continue")
      PaperlessReOptInPage.reOptInWithVerifiedEmail()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario("Re-opt-out by existing PTA email verified customer", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-out from the Re-opt-in interrupt page")
      PaperlessReOptInPage.reOptOut()
      Then("I see the page: You now get tax letters by post")
      PaperlessOptoutPage.waitUntilPageLoad()
      And("I click Continue Opt out button")
      PaperlessOptoutPage.clickOnContinueButton()
      And("I see the page: Why did you choose to go back to paper letters?")
      PaperlessOptOutSurveyPage.waitUntilPageLoad(true)
      And("I click Continue button")
      PaperlessOptOutSurveyPage.clickOnContinueButton()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, verified, email changed, unverified customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I go to Check your settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLinkVerified()
      PaperlessChangeEmailAddressPage.fillChangeEmailPage()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, verified, email changed, bounced customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I navigate to Check your settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLinkVerified()
      PaperlessChangeEmailAddressPage.fillChangeEmailPage()
      And("email is bounced")
      bounceVerifyEmail()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "Re-opt-in page display to existing PTA email opted-in, verified, email changed, verified customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      And("I navigate to Check your settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLinkVerified()
      val verifyNewEmailUrl: String = PaperlessChangeEmailAddressPage.fillChangeEmailPage()
      And("I verify new email address")
      verifyEmail()
      And("I navigate back to Verify your email address page")
      navigateToUrl(verifyNewEmailUrl)
      And("I click on continue button")
      PaperlessVerifyNewEmailPage.clickOnContinueButton()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I click the already opted in email address and continue")
      PaperlessReOptInPage.reOptInWithVerifiedEmail()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario("No Re-opt-in page display to existing PTA email opted-in,unverified customer", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      When("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "Re-opt-in page display to existing PTA email opted-in, unverified, email changed, verified customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I click Close button")
      PaperlessVerifyEmailPage.continueVerifyEmailAddressPage()
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      And("I navigate to Check Your Settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLink()
      val verifyNewEmailUrl: String = PaperlessChangeEmailAddressPage.fillChangeEmailPage()
      And("I verify new email address")
      verifyEmail()
      And("I navigate back to Verify your new email address page")
      navigateToUrl(verifyNewEmailUrl)
      And("I click on continue button")
      PaperlessVerifyNewEmailPage.clickOnContinueButton()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I click the already opted in email address and continue")
      PaperlessReOptInPage.reOptInWithVerifiedEmail()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, unverified, email changed, unverified customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I click Close button")
      PaperlessVerifyEmailPage.continueVerifyEmailAddressPage()
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I navigate to Check Your Settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLink()
      PaperlessChangeEmailAddressPage.fillChangeEmailPage()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, unverified, bounced customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I click Close button")
      PaperlessVerifyEmailPage.continueVerifyEmailAddressPage()
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I navigate to Check Your Settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("email bounced")
      bounceVerifyEmail()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario("Welsh content for the re-opt-in page", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I click toggle link to Welsh")
      selectLanguageWelsh()
      Then("I see the page: Parhau i gael eich llythyrau treth ar-lein")
      PaperlessReOptInPage.waitUntilPageLoad(true)
    }

    Scenario("No Re-opt-in page display to existing PTA opt-out customer", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I opt out from the paperless interrupt page")
      PaperlessInterruptPage.pageTitle()
      PaperlessInterruptPage.fillInterruptPageForOptout()
      When("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario("Opt-out from CYS page after opt-in", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("NoSautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I opt-out from CYS page after navigating from PTA")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      PaperlessCheckYourSettingsPage.waitUntilPageLoad()
      PaperlessCheckYourSettingsPage.clickOnChangeTaxDocumentsLink()
      PaperlessConfirmGettingTaxLettersPage.waitForPageLoad()
      PaperlessConfirmGettingTaxLettersPage.clickOnGetLettersByPost()
      And("I see the page: Why did you choose to go back to paper letters?")
      PaperlessOptOutSurveyPage.waitUntilPageLoad(true)
      And("I click Continue button")
      PaperlessOptOutSurveyPage.clickOnContinueButton()
      Then("I see Post in the Check your settings page")
      PaperlessCheckYourSettingsPage.contentVerification("Tax documents", "Post")
    }

    Scenario("Opt-out from CYS page after re-opt-in", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I click the already opted in email address and continue")
      PaperlessReOptInPage.reOptInWithVerifiedEmail()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I opt-out from CYS page after navigating from PTA")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      PaperlessCheckYourSettingsPage.waitUntilPageLoad()
      PaperlessCheckYourSettingsPage.clickOnChangeTaxDocumentsLink()
      PaperlessConfirmGettingTaxLettersPage.waitForPageLoad()
      PaperlessConfirmGettingTaxLettersPage.clickOnGetLettersByPost()
      And("I see the page: Why did you choose to go back to paper letters?")
      PaperlessOptOutSurveyPage.waitUntilPageLoad(true)
      And("I click Continue button")
      PaperlessOptOutSurveyPage.clickOnContinueButton()
      Then("I see Post in the Check your settings page")
      PaperlessCheckYourSettingsPage.contentVerification("Tax documents", "Post")
    }

    Scenario("Admin Opt-out after opt-in", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("NoSautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I login to Admin Frontend as admin")
      PreferencesAdminPage.loadPage()
      PreferencesAdminPage.adminLogin()
      And("When click on the paperless admin link")
      PreferencesAdminPage.clickOnPaperlessAdmin()
      And("I select search by nino option")
      PreferencesAdminSearchPage.selectNinoRadioOption()
      And("I enter the nino value and click search")
      PreferencesAdminSearchPage.fillIdentifierValueUsingNino()
      And("I click on opt out user link and fill the reason")
      PreferencesAdminSummaryPage.clickOnOptUserOutLink()
      PreferencesAdminSummaryPage.fillReasonToOptOut()
      Then("I should see the user summary page title and success message")
      PreferencesAdminUserSummaryPage.pageTitle()
      PreferencesAdminUserSummaryPage.userOptOutSuccessfullyMessage()
    }

    Scenario("Admin Opt-out after re-opt-in", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("NoSautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("NoSautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I click the already opted in email address and continue")
      PaperlessReOptInPage.reOptInWithVerifiedEmail()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I login to Admin Frontend as admin")
      PreferencesAdminPage.loadPage()
      PreferencesAdminPage.adminLogin()
      And("When click on the paperless admin link")
      PreferencesAdminPage.clickOnPaperlessAdmin()
      And("I select search by nino option")
      PreferencesAdminSearchPage.selectNinoRadioOption()
      And("I enter the nino value and click search")
      PreferencesAdminSearchPage.fillIdentifierValueUsingNino()
      And("I click on opt out user link and fill the reason")
      PreferencesAdminSummaryPage.clickOnOptUserOutLink()
      PreferencesAdminSummaryPage.fillReasonToOptOut()
      Then("I should see the user summary page title and success message")
      PreferencesAdminUserSummaryPage.pageTitle()
      PreferencesAdminUserSummaryPage.userOptOutSuccessfullyMessage()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, verified, email changed, changed email bounced customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I go to Check your settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLinkVerified()
      And("The changed email is bounced")
      bounceChangedEmail()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "No Re-opt-in page display to existing PTA email opted-in, verified, email changed, verified and changed email bounced customer",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      And("I navigate to PTA account")
      navigateToAccount(pta)
      And("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
      When("I go to Check your settings page")
      PaperlessPTAHomePage.navigateToCheckYourSettings()
      And("I change email address")
      PaperlessCheckYourSettingsPage.clickOnChangeEmailAddressLinkVerified()
      And("The verify and changed emails are bounced")
      bounceVerifyEmail()
      bounceChangedEmail()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario(
      "Re-opt-in by existing PTA email verified customer by changing email address - sautr 2",
      PtaPaperlessTests
    ) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr2", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I choose A new email address link and enter email address")
      PaperlessReOptInPage.reOptInWithNewEmail()
      And("I click Close button")
      PaperlessVerifyEmailPage.continueVerifyEmailAddressPage()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

    Scenario("Re-opt-in by existing PTA email verified customer by changing email address", PtaPaperlessTests) {
      Given("I am logged into PTA account with nino and sautr enrolment")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      PaperlessInterruptPage.pageTitle()
      And("I am unverified for paperless")
      PaperlessInterruptPage.fillInterruptPageForOptin()
      PaperlessEmailPage.fillEmailPage()
      PaperlessVerifyEmailPage.pageTitle()
      And("I verify the email address")
      verifyEmail()
      When("I update major version")
      setVersionMajor()
      And("I am logged into PTA account")
      LoginUsingAuthWizardPage.pageLoad()
      LoginUsingAuthWizardPage.loginIntoAccountByAuthWizard("sautr", pta)
      And("I see the page: Keep getting your tax letters online")
      PaperlessReOptInPage.waitUntilPageLoad()
      And("I re-opt-in and see the page: Which email do you want to use for your tax letters?")
      PaperlessReOptInPage.reOptIn()
      And("I choose A new email address link and enter email address")
      PaperlessReOptInPage.reOptInWithNewEmail()
      And("I click Close button")
      PaperlessVerifyEmailPage.continueVerifyEmailAddressPage()
      Then("I see the page: Personal Tax Account")
      PaperlessPTAHomePage.waitUntilPageLoad()
    }

  }
  override def beforeEach(): Unit = {
    super.beforeEach()
    deleteMongoRecordsFromCollection("preferences")
  }

}
